apex-wilderness/objects/Adventure_Park__c/Adventure_Park__c.object-meta.xml
<CustomObject>
    <description>Represents one park where adventure is to be had!</description>
    <label>Adventure Park</label>
    <nameField>
        <label>Park Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Adventure Parks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Park_Of_Interest__c/Park_Of_Interest__c.object-meta.xml
<CustomObject>
    <description>A junction object between Lead/Contact and an Adventure Park. Allows one person to be interested in many adventure parks.</description>
    <label>Park Of Interest</label>
    <nameField>
        <displayFormat>POI-{000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Parks Of Interest</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

apex-wilderness/objects/Park_Of_Interest__c/fields/Adventure_Park__c.field-meta.xml
<CustomField>
    <fullName>Adventure_Park__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Adventure Park</label>
    <referenceTo>Adventure_Park__c</referenceTo>
    <relationshipLabel>Parks Of Interest</relationshipLabel>
    <relationshipName>Parks_Of_Interest</relationshipName>
    <type>Lookup</type>
</CustomField>

apex-wilderness/objects/Park_Of_Interest__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Parks Of Interest</relationshipLabel>
    <relationshipName>Parks_Of_Interest</relationshipName>
    <type>Lookup</type>
</CustomField>

apex-wilderness/objects/Park_Of_Interest__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Parks Of Interest</relationshipLabel>
    <relationshipName>Parks_Of_Interest</relationshipName>
    <type>Lookup</type>
</CustomField>

apex-backwoods/objects/Park_Tour__c/Park_Tour__c.object-meta.xml
<CustomObject>
    <description>A junction object between Leads/Contact and Adventure Parks. Represents an actual tour of a park, which differentiates itself from POIs. Parks of Interest represents merely interest and desired park adventure. But a Park Tour is an actual tour of the adventure.</description>
    <label>Park Tour</label>
    <nameField>
        <displayFormat>PT-{000}</displayFormat>
        <label>Park Tour Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Park Tour</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

apex-backwoods/objects/Park_Tour__c/fields/Adventure_Park__c.field-meta.xml
<CustomField>
    <fullName>Adventure_Park__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Adventure Park</label>
    <referenceTo>Adventure_Park__c</referenceTo>
    <relationshipLabel>Park Tour</relationshipLabel>
    <relationshipName>Park_Tour</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Park_Tour__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Park Tour</relationshipLabel>
    <relationshipName>Park_Tour</relationshipName>
    <type>Lookup</type>
</CustomField>

apex-backwoods/objects/Park_Tour__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Park Tour</relationshipLabel>
    <relationshipName>Park_Tour</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Park_Tour__c/fields/Park_Interest_Rating__c.field-meta.xml
<CustomField>
    <fullName>Park_Interest_Rating__c</fullName>
    <label>Park Interest Rating</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Park_Tour__c/fields/POI_Synced_On_Insert__c.field-meta.xml
<CustomField>
    <fullName>POI_Synced_On_Insert__c</fullName>
    <defaultValue>false</defaultValue>
    <label>POI Synced On Insert</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/ParkTourTrigger_Handler.cls
public without sharing class ParkTourTrigger_Handler {

    public void onBeforeInsert(List<Park_Tour__c> newSiteVisits) {
        List<Park_Tour__c> siteVisitsForCommunityOfInterestRatingUpdate = new List<Park_Tour__c>();
        List<Park_Tour__c> siteVisitsToUpdateReturnVisitorAndMaybeAccountId = new List<Park_Tour__c>();
        for (Park_Tour__c newSiteVisit : newSiteVisits) {
            //When Park_Interest_Rating__c is not populated. Comes from Walk In Form
            if (newSiteVisit.Park_Interest_Rating__c == null) {
                siteVisitsForCommunityOfInterestRatingUpdate.add(newSiteVisit);
            }
            siteVisitsToUpdateReturnVisitorAndMaybeAccountId.add(newSiteVisit);
        }

        if (siteVisitsForCommunityOfInterestRatingUpdate.size() > 0) {
            ParkTourTrigger_Helper.getCOIrating(siteVisitsForCommunityOfInterestRatingUpdate);
        }

        if (siteVisitsToUpdateReturnVisitorAndMaybeAccountId.size() > 0) {
            ParkTourTrigger_Helper.checkNewVisitor(siteVisitsToUpdateReturnVisitorAndMaybeAccountId);
        }
    }

    public void onAfterInsert(List<Park_Tour__c> newList, Map<Id, Park_Tour__c> newVisitsMap) {
        List<Park_Tour__c> updateCOIList = new List<Park_Tour__c>();
        Set<Id> leadIds = new Set<Id>();
        Set<Id> communitySiteIds = new Set<Id>();
        Set<Id> contactIds = new Set<Id>();
        //todo: I question the need for the Map<Id, SiteVisit__c>
        //      - validate in dependencies
        //      - refactor in Trigger
        for (Park_Tour__c newSiteVisit : newVisitsMap.values()) {
            if (newSiteVisit.Park_Interest_Rating__c != null && newSiteVisit.POI_Synced_On_Insert__c == false) {

                if (!updateCOIList.contains(newSiteVisit)) {
                    updateCOIList.add(newSiteVisit);
                }
            }
            if (newSiteVisit.Lead__c != null) {
                leadIds.add(newSiteVisit.Lead__c);
            }
            if (newSiteVisit.Adventure_Park__c != null) {
                communitySiteIds.add(newSiteVisit.Adventure_Park__c);
            }
            if (newSiteVisit.Contact__c != null) {
                contactIds.add(newSiteVisit.Contact__c);
            }
        }

        Set<Id> accountIds = new Set<Id>();
        List<Park_Of_Interest__c> communitiesOfInterestForUpdate = new List<Park_Of_Interest__c>();
        if (updateCOIList != null && !updateCOIList.isEmpty()) {
            communitiesOfInterestForUpdate = ParkTourTrigger_Helper.updatCOIRating(updateCOIList);
        }

        if (communitiesOfInterestForUpdate != null && !communitiesOfInterestForUpdate.isEmpty()) {
            update communitiesOfInterestForUpdate;
        }
    }

    public void onAfterUpdate(Map<Id, Park_Tour__c> newMap, Map<Id, Park_Tour__c> oldMap) {
        List<Park_Tour__c> updateCOIList = new List<Park_Tour__c>();
        List<Park_Of_Interest__c> coisForUpdate = new List<Park_Of_Interest__c>();
        for (Park_Tour__c sv : newMap.values()) {
            Park_Tour__c oldSV = oldMap.get(sv.Id);
            if (sv.Park_Interest_Rating__c != oldSV.Park_Interest_Rating__c) {
                if (!updateCOIList.contains(sv)) {
                    updateCOIList.add(sv);
                }
            }
        }

        if (updateCOIList != null && !updateCOIList.isEmpty()) {
            coisForUpdate = ParkTourTrigger_Helper.updatCOIRating(updateCOIList);
        }

        if (coisForUpdate != null && !coisForUpdate.isEmpty()) {
            update coisForUpdate;
        }
    }
}