apex-wilderness/objects/Adventure_Park__c/Adventure_Park__c.object-meta.xml
<CustomObject>
    <description>Represents one park where adventure is to be had!</description>
    <label>Adventure Park</label>
    <nameField>
        <label>Park Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Adventure Parks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

apex-backwoods/objects/Adventure_Park__c/fields/Open_Date__c.field-meta.xml
<CustomField>
    <fullName>Open_Date__c</fullName>
    <description>The date the park will be or was opened to adventurers.</description>
    <label>Open Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Adventure_Park__c/fields/Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Price_Book__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Price Book</label>
    <referenceTo>Pricebook2</referenceTo>
    <relationshipLabel>Adventure Parks</relationshipLabel>
    <relationshipName>Adventure_Parks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AdventureParkTrigger_Handler.cls
public with sharing class AdventureParkTrigger_Handler {

    public static void onBeforeUpdate(Map<Id, Adventure_Park__c> newMap, Map<Id, Adventure_Park__c> oldMap) {

        List<Adventure_Park__c> needPB = new List<Adventure_Park__c>();
        for (Adventure_Park__c cs : newMap.values()) {
            if (cs.Open_Date__c >= Date.today() && cs.Is_Active__c == false) {
                cs.Is_Active__c = true;
            }
            if (cs.Price_Book__c == null) {
                needPB.add(cs);
            }
        }
        getPricebooks(needPB);

    }

    public static void onBeforeInsert(List<Adventure_Park__c> comms) {

        List<Adventure_Park__c> needPB = new List<Adventure_Park__c>();
        for (Adventure_Park__c c : comms) {
            if (c.Price_Book__c == null) {
                needPB.add(c);
            }
        }
        getPricebooks(needPB);

    }

    private static void getPricebooks(List<Adventure_Park__c> needPB) {
        Map<Id, Pricebook2> pbMap = AdventureParkTrigger_Helper.createPB(needPB);
        for (Adventure_Park__c c : needPB) {
            if (pbMap.get(c.Id) != null) {
                c.Price_Book__c = pbMap.get(c.Id).Id;
            }
        }
    }

    public static void onAfterUpdate(Map<Id, Adventure_Park__c> newMap, Map<Id, Adventure_Park__c> oldMap) {
        Set<Id> commSiteIds = new Set<Id>();
        for (Id commId : newMap.keySet()) {
            if (newMap.get(commId).Open_Date__c != oldMap.get(commId).Open_Date__c ||
                newMap.get(commId).Is_Active__c != oldMap.get(commId).Is_Active__c
            ) {
                commSiteIds.add(commId);
            }
        }

        if (commSiteIds != null && !commSiteIds.isEmpty()) {
            //todo: close all related and inactivate all Parks of Interest
        }
    }
}